src/Entity/Posts.php
<?php

namespace App\Entity;

use App\Repository\PostsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostsRepository::class)]
class Posts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $img_url = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $body = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getImgUrl(): ?string
    {
        return $this->img_url;
    }

    public function setImgUrl(string $img_url): static
    {
        $this->img_url = $img_url;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): static
    {
        $this->body = $body;

        return $this;
    }
}

src/Form/PostsType.php
<?php

namespace App\Form;

use App\Entity\Posts;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class PostsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', null, ['label' => 'Título'])
            ->add('img_url', null, ['label'=> 'URL de la imagen'])
            ->add('body', null, ['label' => 'Cuerpo del vox'] )
            ->add('Guardar', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Posts::class,
        ]);
    }
}

src/Controller/PageController.php
<?php

namespace App\Controller;
use App\Entity\Posts;
use App\Form\PostsType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Doctrine\ORM\EntityManagerInterface;


class PageController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function home(EntityManagerInterface $entityManager, Request $request): Response
    {
        $session = $request->getSession();
        $username = $session->get('username');

        $posts = $entityManager->getRepository(Posts::class)->findAll();


        return $this->render("home.html.twig", ["username" => $username, "posts" => $posts]);
    }

    #[Route('/form', name: 'form')]
    public function form(EntityManagerInterface $entityManager, Request $request): Response
    {
        // Validamos que este logueado 
        $session = $request->getSession();
        $username = $session->get('username');
        
        $form = $this->createForm(PostsType::class);
        if ($username == null || $username == '') {
            return $this->redirect("login"); // Si no está logueado lo mandamos al auth
        } 
                
        $form->handleRequest($request);
        
        if ($form->isSubmitted()) {
            
            $submitedData = $form->getData();
            $submitedData->setUsername($username);
            $entityManager->persist($submitedData);
            $entityManager->flush();
            
            return $this->redirectToRoute('home');
        }
        
        return $this->render("form.html.twig", ["username"=> $username,"form"=> $form->createView()]);
                
    }
    //TODO: Muchos returns, eso es code smell. Corregir

    #[Route('/post', name: 'post')]
    public function post(Request $request, EntityManagerInterface $entityManager): Response
    {
        $id = $request->get('id');
        $post = $entityManager
            ->getRepository(Posts::class)
            ->findOneBy(array('id'=> $id));

        return $this->render("post.html.twig", ["post"=> $post]);
    }

    #[Route('/login', name: 'login')]
    public function login(Request $request): Response
    {
        $session = $request->getSession();
        $username = $session->get('username');

        if ($username != null || $username != '') {
            return $this->redirectToRoute("home"); // Si está logueado lo mandamos al home
        } 

        $form = $this->createFormBuilder()
        ->add('username', TextType::class, [
            'label' => 'Nickname' 
        ])
        ->add('submit', SubmitType::class, [
            'label' => 'Enviar' 
        ])
        ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $data = $form->getData();
            $session->set('username', $data['username']);
            return $this->redirectToRoute("home");
        }

        $view = $this->render("auth.html.twig", [
            "form" => $form,
        ]);

        return $view;
    }

    #[Route('/logout', name: 'logout')]
    public function logout(Request $request): Response
    {
        $session = $request->getSession();
        $session->clear();
        return $this->redirectToRoute("home");
        
    }

    private function userIsLogged($session) {
        return isset($session["username"]) && 
            $session["username"] != null;
    }
   

}

templates/auth.html.twig
{% extends 'base.html.twig' %}


{% block body %}

<div class="form-container">

{{form(form)}}

</div>


{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
      <link rel="shortcut icon" href="{{ asset('images/favicon.png') }}">
        <title>{% block title %}VOXINGA!{% endblock %}</title>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>


  <nav class="navbar navbar-expand-lg bg-body-tertiary " data-bs-theme="dark" >
  <div class="container-fluid">
    <a class="navbar-brand" href="/">VOXINGA!</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/form">Crea un vox!</a>
        </li>
      </ul>


          {% if  app.session.get("username")%}

            <a class="nav-link active" aria-current="page" href="/logout">Cerrar sesión</a>

          {% else %}

            <a class="nav-link active" aria-current="page" href="/login">Inicia sesión</a>

          {% endif %}

    
    </div>
  </div>
</nav>


        {% block body %}{% endblock %}
    </body>
</html>
 

templates/form.html.twig
{% extends 'base.html.twig' %}


{% block body %}

<div class="form-container">

{{form(form)}}
</div>
{% endblock %}

templates/home.html.twig
{% extends 'base.html.twig' %}


{% block body %}
	<main class="vox-container">

		{%for post in posts %}

			<a href="/post/?id={{post.id}}">
				<div class="vox" style="background-image: url('{{ post.imgUrl }}'); background-size: cover;">
					<h2>{{post.title}}</h2>
				</div>
			</a>

		{% endfor %}
      
	</main>


{% endblock %}

templates/post.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<main class="post-container">
<div class="post">

<h1>{{post.title}}</h1>
<img class="post-img" src="{{post.imgUrl}}">
<p>{{post.body}}</p>



</div>

</main>
{% endblock %}